### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by ItzMeLeo9827** [JaylyDev/terminator#35]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.
When Spawning the terminator, it is invisible and if there is a custom cape, it is black and pink and the terminator is invisible. and the #summon custom command also makes it invisible, shield in wrong place( creeper shield is not with the bug its my texture pack(texture pack working fine.))

**Describe the solution you'd like**
The terminator wont be invisible and no glitched cape
![image_2022-01-24_201911](https://user-images.githubusercontent.com/98258625/150781766-a3dbb3a4-9a44-4de0-ac1e-ccb44c4143cb.png)
![image_2022-01-24_202005](https://user-images.githubusercontent.com/98258625/150781877-ea478e61-d125-4863-a27c-1c3f30ad8103.png)
![image_2022-01-24_202339](https://user-images.githubusercontent.com/98258625/150782352-9d7c8c17-8a5d-48db-b023-c267e1523d16.png)

**Describe alternatives you've considered**
No
**Additional context**
No

**Comment by JaylyDev** [comment]
redo the report using bug report template instead of suggestion template. You can edit the report and submit again with this format [Bug report template](https://github.com/JaylyDev/terminator/issues/new?assignees=&labels=bug&template=bug_report.md&title=) and label this as a bug, or create a new issue.
